feat: make metrics sink address support hostnames
mozilla-services/merino pull request #142
Opened 2021-09-23 15:13 UTC by Dexterp37

This fixes [this JIRA ticket](https://mozilla-hub.atlassian.net/browse/CONSVC-1263).

2021-09-23 16:05 UTC, mythmon requested changes

2021-09-23 16:05 UTC, mythmon commented on config/test.yaml
> +  sink_port: 0
I think that this should default to `8125`. `0.0.0.0` is a sort-of-sensical port for this to be on, but port 0 definitely doesn't make sense here.
```suggestion
  sink_port: 8125
```

2021-09-23 16:54 UTC, mythmon approved these changes

2021-09-27 07:21 UTC, Dexterp37 commented on merino-integration-tests/src/utils/test_tools.rs
> +        settings.metrics.sink_port, 0,
```suggestion
        settings.metrics.sink_port, 8125,
```

2021-09-28 16:46 UTC, merged