feat: Add sub-microsecond precision using floats for timer metrics
mozilla-services/merino pull request #219
Opened 2021-11-17 23:08 UTC by mythmon

2021-11-18 00:01 UTC, pjenvey requested changes

2021-11-18 00:01 UTC, pjenvey commented on merino-suggest/src/metrics.rs
> +/// Only `Duration types are valid.
```suggestion
/// Only `Duration` types are valid.
```

2021-11-18 00:29 UTC, mythmon commented
The check failure is `cargo audit`. I've made #220 to handle that.

2021-11-18 00:49 UTC, pjenvey approved these changes

2021-11-18 13:30 UTC, Dexterp37 commented
Do we need to update the data docs ?

2021-11-18 16:50 UTC, mythmon commented
The data docs currently say

> A histogram that records the amount of time, in microseconds, that the adM Remote Settings provider took to generate suggestions.

That doesn't specify what the precision of those microseconds are, so I don't think we need to update the docs.

2021-11-24 19:16 UTC, mythmon commented
Rebased to pick up CI changes.

2021-11-24 21:23 UTC, merged