feat(adm): implement reconfigure for RemoteSettings provider
mozilla-services/merino pull request #340
Opened 2022-02-19 02:13 UTC by ncloudioj

~~WIP, will add some tests later.~~

 It allows us to reconfigure `resync_interval` and `suggestion_score` for Remote Settings providers. The reconfiguration for `bucket` and `collection` is not currently supported as we don't have a clear use case for those settings.

This fixes [CONSVC-1619](https://mozilla-hub.atlassian.net/browse/CONSVC-1619).

2022-02-22 21:48 UTC, ncloudioj commented
OK, it's ready for review now.

I also added a new subfolder under `merino-integration-test` for all provider reconfigure integration tests.

2022-02-23 23:05 UTC, pjenvey requested changes

2022-02-24 01:11 UTC, ncloudioj commented on merino-adm/src/remote_settings/mod.rs
> +            let suggestion_score = Self::parse_suggestion_score(new_config.suggestion_score)?;
Nice catch, thanks!

2022-02-24 01:25 UTC, pjenvey approved these changes

2022-02-24 13:09 UTC, merged